ALTER TABLE ACCOUNTS ADD COLUMN SORT VARCHAR(10);
UPDATE ACCOUNTS SET SORT = TITLE;
ALTER TABLE ACCOUNTS MODIFY SORT VARCHAR(10) NOT NULL;

ALTER TABLE CATEGORIES ADD COLUMN SORT VARCHAR(10);
UPDATE CATEGORIES SET SORT = TITLE;
ALTER TABLE CATEGORIES MODIFY SORT VARCHAR(10) NOT NULL;
