CREATE TABLE USERS (
  ID       INTEGER       NOT NULL AUTO_INCREMENT,
  LOGIN    VARCHAR(10)   NOT NULL,
  PASSWORD VARCHAR(1024) NOT NULL,
  ADMIN    BOOLEAN       NOT NULL,
  BLOCKED  BOOLEAN       NOT NULL,
  TOKEN    VARCHAR(36)   NOT NULL,
  EXPIRES  TIMESTAMP     NOT NULL,
  PRIMARY KEY (ID)
);
