DROP TABLE IF EXISTS OPERATIONS;
DROP TABLE IF EXISTS ACCOUNTS;
DROP TABLE IF EXISTS CATEGORIES;
DROP TABLE IF EXISTS CURRENCIES;

CREATE TABLE CURRENCIES (
  ID    BIGINT       NOT NULL AUTO_INCREMENT,
  CODE  VARCHAR(3)   NOT NULL,
  TITLE VARCHAR(250) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE CATEGORIES (
  ID    BIGINT       NOT NULL AUTO_INCREMENT,
  TITLE VARCHAR(250) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE ACCOUNTS (
  ID          BIGINT       NOT NULL,
  CURRENCY_ID BIGINT       NOT NULL,
  TITLE       VARCHAR(250) NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_ACCOUNTS_CURRENCIES FOREIGN KEY (CURRENCY_ID) REFERENCES CURRENCIES (ID)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
);

CREATE TABLE OPERATIONS (
  ID          BIGINT         NOT NULL,
  ACCOUNT_ID  BIGINT         NOT NULL,
  CATEGORY_ID BIGINT         NOT NULL,
  DAY         DATE           NOT NULL,
  AMOUNT      NUMERIC(20, 4) NOT NULL,
  NOTE        VARCHAR(250),
  PRIMARY KEY (ID),
  CONSTRAINT FK_OPERATIONS_ACCOUNTS FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ID)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT FK_OPERATIONS_CATEGORIES FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES (ID)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
);
